// lang.js - 100 languages FULL - FIXED IDs for langM/langGrid
var LANGS = [
{c:'en',n:'English',f:'🇺🇸'},{c:'fr',n:'Français',f:'🇫🇷'},{c:'es',n:'Español',f:'🇪🇸'},{c:'ru',n:'Русский',f:'🇷🇺'},{c:'ar',n:'العربية',f:'🇸🇦'},{c:'hi',n:'हिन्दी',f:'🇮🇳'},{c:'zh',n:'中文',f:'🇨🇳'},{c:'pt',n:'Português',f:'🇵🇹'},{c:'de',n:'Deutsch',f:'🇩🇪'},{c:'tr',n:'Türkçe',f:'🇹🇷'},
{c:'it',n:'Italiano',f:'🇮🇹'},{c:'ja',n:'日本語',f:'🇯🇵'},{c:'ko',n:'한국어',f:'🇰🇷'},{c:'nl',n:'Nederlands',f:'🇳🇱'},{c:'pl',n:'Polski',f:'🇵🇱'},{c:'id',n:'Indonesia',f:'🇮🇩'},{c:'ms',n:'Melayu',f:'🇲🇾'},{c:'th',n:'ไทย',f:'🇹🇭'},{c:'vi',n:'Tiếng Việt',f:'🇻🇳'},{c:'uk',n:'Українська',f:'🇺🇦'},
{c:'bn',n:'বাংলা',f:'🇧🇩'},{c:'fa',n:'فارسی',f:'🇮🇷'},{c:'ur',n:'اردو',f:'🇵🇰'},{c:'sw',n:'Kiswahili',f:'🇰🇪'},{c:'ha',n:'Hausa',f:'🇳🇬'},{c:'yo',n:'Yorùbá',f:'🇳🇬'},{c:'ig',n:'Igbo',f:'🇳🇬'},{c:'am',n:'አማርኛ',f:'🇪🇹'},{c:'zu',n:'Zulu',f:'🇿🇦'},{c:'af',n:'Afrikaans',f:'🇿🇦'},
{c:'ro',n:'Română',f:'🇷🇴'},{c:'el',n:'Ελληνικά',f:'🇬🇷'},{c:'cs',n:'Čeština',f:'🇨🇿'},{c:'hu',n:'Magyar',f:'🇭🇺'},{c:'sv',n:'Svenska',f:'🇸🇪'},{c:'no',n:'Norsk',f:'🇳🇴'},{c:'da',n:'Dansk',f:'🇩🇰'},{c:'fi',n:'Suomi',f:'🇫🇮'},{c:'he',n:'עברית',f:'🇮🇱'},{c:'fil',n:'Filipino',f:'🇵🇭'},
{c:'my',n:'မြန်မာ',f:'🇲🇲'},{c:'km',n:'ខ្មែរ',f:'🇰🇭'},{c:'lo',n:'ລາວ',f:'🇱🇦'},{c:'ne',n:'नेपाली',f:'🇳🇵'},{c:'si',n:'සිංහල',f:'🇱🇰'},{c:'uz',n:'Oʻzbek',f:'🇺🇿'},{c:'kk',n:'Қазақ',f:'🇰🇿'},{c:'az',n:'Azərbaycan',f:'🇦🇿'},{c:'ka',n:'ქართული',f:'🇬🇪'},{c:'hy',n:'Հայերեն',f:'🇦🇲'},
{c:'bg',n:'Български',f:'🇧🇬'},{c:'sr',n:'Српски',f:'🇷🇸'},{c:'hr',n:'Hrvatski',f:'🇭🇷'},{c:'sk',n:'Slovenčina',f:'🇸🇰'},{c:'sl',n:'Slovenščina',f:'🇸🇮'},{c:'lt',n:'Lietuvių',f:'🇱🇹'},{c:'lv',n:'Latviešu',f:'🇱🇻'},{c:'et',n:'Eesti',f:'🇪🇪'},{c:'is',n:'Íslenska',f:'🇮🇸'},{c:'mt',n:'Malti',f:'🇲🇹'}
];

var T = {
en:{bets:"BETS THIS WEEK - 7 days",betsDesc:"Choose coin, predict UP/DROP/STEADY, win 6x in 7 days",global:"GLOBAL LIVE",globalDesc:"Live bets from all users worldwide",inviteBtn:"INVITE 10 USDT",inviteDesc:"Invite people & get 10 USDT per person instantly to your EARNING!",deposit:"DEPOSIT: Your total deposit",earning:"MY EARNING - Live",earningDesc:"Your profits from winning bets + invites",yourBets:"Your Bets - All your active bets for 7 days",buyTitle:"BUYCRYPT - Buy BTC/ETH/SOL",buyDesc:"Choose coin you want to buy, choose amount, send to address, verify",betTitle:"BETCRYPT - Predict & Win",betDesc1:"1. Choose coin you are predicting",betDesc2:"2. Will coin go:",betDesc3:"3. Choose what you are betting for 7 days",up:"UP - Price will go UP",drop:"DROP - Price will DROP",steady:"STEADY - Price stays same",withdrawTitle:"WITHDRAW - Min 50k + 5 invites",withdrawDesc:"You need 50k USDT + 5 friends invited to withdraw",inviteTitle:"INVITE 10 USDT",placeBtn:"PLACE BET FOR 7 DAYS",verifyBtn:"VERIFY PAYMENT",submitBtn:"SUBMIT WITHDRAWAL",copy:"COPY ADDRESS",addrBox:"Send to this address:"},
fr:{bets:"PARIS DE LA SEMAINE - 7 jours",betsDesc:"Choisissez la pièce, prédisez HAUT/BAISSE/STABLE, gagnez 6x en 7 jours",global:"EN DIRECT MONDIAL",globalDesc:"Paris en direct de tous les utilisateurs",inviteBtn:"INVITER 10 USDT",inviteDesc:"Invitez des gens et gagnez 10 USDT par personne instantanément!",deposit:"DÉPÔT: Votre dépôt total",earning:"MES GAINS - En direct",earningDesc:"Vos profits des paris gagnants + invitations",yourBets:"Vos Paris - Tous vos paris actifs",buyTitle:"ACHETER CRYPTO - Acheter BTC/ETH/SOL",buyDesc:"Choisissez la pièce, choisissez le montant, envoyez à l'adresse",betTitle:"PARI CRYPTO - Prédisez et Gagnez",betDesc1:"1. Choisissez la pièce que vous prédisez",betDesc2:"2. La pièce va:",betDesc3:"3. Choisissez ce que vous pariez pour 7 jours",up:"HAUT - Le prix va monter",drop:"BAISSE - Le prix va baisser",steady:"STABLE - Le prix reste pareil",withdrawTitle:"RETRAIT - Min 50k + 5 invitations",withdrawDesc:"Vous avez besoin de 50k USDT + 5 amis invités pour retirer",inviteTitle:"INVITER 10 USDT",placeBtn:"PLACER LE PARI 7 JOURS",verifyBtn:"VÉRIFIER LE PAIEMENT",submitBtn:"SOUMETTRE LE RETRAIT",copy:"COPIER L'ADRESSE",addrBox:"Envoyer à cette adresse:"},
es:{bets:"APUESTAS ESTA SEMANA - 7 días",betsDesc:"Elige moneda, predice SUBIDA/BAJADA/ESTABLE, gana 6x en 7 días",global:"GLOBAL EN VIVO",globalDesc:"Apuestas en vivo de todos los usuarios",inviteBtn:"INVITAR 10 USDT",inviteDesc:"¡Invita personas y gana 10 USDT por persona al instante!",deposit:"DEPÓSITO: Tu depósito total",earning:"MIS GANANCIAS - En vivo",earningDesc:"Tus ganancias de apuestas ganadoras + invitaciones",yourBets:"Tus Apuestas - Todas tus apuestas activas",buyTitle:"COMPRAR CRIPTO - Comprar BTC/ETH/SOL",buyDesc:"Elige moneda, elige monto, envía a dirección",betTitle:"APUESTA CRIPTO - Predice y Gana",betDesc1:"1. Elige la moneda que predices",betDesc2:"2. La moneda irá:",betDesc3:"3. Elige lo que apuestas por 7 días",up:"SUBIDA - El precio subirá",drop:"BAJADA - El precio bajará",steady:"ESTABLE - El precio se queda igual",withdrawTitle:"RETIRAR - Min 50k + 5 invitados",withdrawDesc:"Necesitas 50k USDT + 5 amigos invitados para retirar",inviteTitle:"INVITAR 10 USDT",placeBtn:"APOSTAR POR 7 DÍAS",verifyBtn:"VERIFICAR PAGO",submitBtn:"ENVIAR RETIRO",copy:"COPIAR DIRECCIÓN",addrBox:"Enviar a esta dirección:"},
ru:{bets:"СТАВКИ НА НЕДЕЛЮ - 7 дней",betsDesc:"Выбери монету, предскажи ВВЕРХ/ВНИЗ/РОВНО, выиграй 6x за 7 дней",global:"ГЛОБАЛ ЛАЙВ",globalDesc:"Живые ставки всех пользователей",inviteBtn:"ПРИГЛАСИТЬ 10 USDT",inviteDesc:"Приглашай людей и получай 10 USDT за каждого мгновенно!",deposit:"ДЕПОЗИТ: Твой общий депозит",earning:"МОЙ ЗАРАБОТОК - Лайв",earningDesc:"Твои прибыли от выигранных ставок + приглашений",yourBets:"Мои Ставки - Все твои активные ставки",buyTitle:"КУПИТЬ КРИПТУ - Купить BTC/ETH/SOL",buyDesc:"Выбери монету, выбери сумму, отправь на адрес",betTitle:"СТАВКА КРИПТЫ - Предскажи и Выиграй",betDesc1:"1. Выбери монету которую предсказываешь",betDesc2:"2. Монета пойдет:",betDesc3:"3. Выбери что ставишь на 7 дней",up:"ВВЕРХ - Цена пойдет вверх",drop:"ВНИЗ - Цена упадет",steady:"РОВНО - Цена останется",withdrawTitle:"ВЫВОД - Мин 50к + 5 приглашений",withdrawDesc:"Нужно 50к USDT + 5 друзей для вывода",inviteTitle:"ПРИГЛАСИТЬ 10 USDT",placeBtn:"СДЕЛАТЬ СТАВКУ НА 7 ДНЕЙ",verifyBtn:"ПРОВЕРИТЬ ОПЛАТУ",submitBtn:"ЗАПРОСИТЬ ВЫВОД",copy:"КОПИРОВАТЬ АДРЕС",addrBox:"Отправить на этот адрес:"},
ha:{bets:"BET NA MAKO - kwana 7",betsDesc:"Zabi coin, yi hasashen UP/DROP/STEADY, ci 6x a kwana 7",global:"RAYUWA TA DUNIYA",globalDesc:"Bet na rayuwa daga duk masu amfani",inviteBtn:"GAYYATA 10 USDT",inviteDesc:"Gayyata mutane kuma sami 10 USDT kowane mutum nan da nan!",deposit:"AJIYA: Jimlar ajiyarka",earning:"RIBATA - Rayuwa",earningDesc:"Ribarka daga nasar bet + gayyata",yourBets:"Bet dina - Duk bet masu aiki",buyTitle:"SAYI CRYPTO - Sayi BTC/ETH/SOL",buyDesc:"Zabi coin da kake son saya, zabi adadi, aika zuwa adireshi",betTitle:"BET CRYPTO - Yi Hasashe & Ci",betDesc1:"1. Zabi coin da kake hasashen",betDesc2:"2. Coin zai tafi:",betDesc3:"3. Zabi abin da kake bet na kwana 7",up:"UP - Farashi zai tashi",drop:"DROP - Farashi zai fadi",steady:"STEADY - Farashi zai tsaya",withdrawTitle:"CIRE KUDI - Min 50k + gayyata 5",withdrawDesc:"Kana buƙatar 50k USDT + abokai 5 da aka gayyata don cirewa",inviteTitle:"GAYYATA 10 USDT",placeBtn:"YI BET NA KWANA 7",verifyBtn:"TABBTAR DA BIYA",submitBtn:"MIKA CIRE KUDI",copy:"KWAFI ADIRESHI",addrBox:"Aika zuwa wannan adireshi:"},
yo:{bets:"BET TI OSE YII - ojo 7",betsDesc:"Yan coin, sọ UP/DROP/STEADY, gba 6x ni ojo 7",global:"LIVE AGBAYE",globalDesc:"Bet laaye lati gbogbo awon olumulo",inviteBtn:"PE 10 USDT",inviteDesc:"Pe eniyan ati gba 10 USDT fun enikan lesekese!",deposit:"IDOGO: Lapapọ idogo rẹ",earning:"ÈRÈ MI - Laaye",earningDesc:"Èrè rẹ lati bet ti o bori + pipe",yourBets:"Bet Mi - Gbogbo bet ti o nṣiṣẹ",buyTitle:"RA CRYPTO - Ra BTC/ETH/SOL",buyDesc:"Yan coin ti o fẹ ra, yan iye, firanṣẹ si adirẹsi",betTitle:"BET CRYPTO - Sọ Asọtẹlẹ & Bori",betDesc1:"1. Yan coin ti o n sọ asọtẹlẹ",betDesc2:"2. Coin yoo lọ:",betDesc3:"3. Yan ohun ti o n bet fun ojo 7",up:"OKE - Iye owo yoo goke",drop:"ISALẸ - Iye owo yoo sọkalẹ",steady:"DURO - Iye owo yoo duro",withdrawTitle:"YO KUDI - Min 50k + pe 5",withdrawDesc:"O nilo 50k USDT + ọrẹ 5 ti a pe lati yọ kudi",inviteTitle:"PE 10 USDT",placeBtn:"GHE BET FUN OJO 7",verifyBtn:"JẸRISI OWO SAN",submitBtn:"FI YO KUDI RANṢẸ",copy:"DA ADIRESI KO",addrBox:"Firanṣẹ si adirẹsi yii:"},
ig:{bets:"BET NKE IZUUKA - ubochi 7",betsDesc:"Họrọ mkpụrụ ego, buru amụma UP/DROP/STEADY, merie 6x na ubochi 7",global:"NDỤ ỤWA",globalDesc:"Bet dị ndụ site na ndị ọrụ niile",inviteBtn:"KPỌ 10 USDT",inviteDesc:"Kpọọ ndị mmadụ & nweta 10 USDT kwa onye ozugbo!",deposit:"NKWỤNYE: Mkpokọta nkwụnye gị",earning:"URU M - Ndụ",earningDesc:"Uru gị site na mmeri bet + ịkpọ oku",yourBets:"Bet M - Bet niile na-arụ ọrụ",buyTitle:"ZỤTA CRYPTO - Zụta BTC/ETH/SOL",buyDesc:"Họrọ mkpụrụ ego ịchọrọ ịzụta, họrọ ego, ziga na adreesị",betTitle:"BET CRYPTO - Buru amụma & Merie",betDesc1:"1. Họrọ mkpụrụ ego ị na-ebu amụma",betDesc2:"2. Mkpụrụ ego ga-aga:",betDesc3:"3. Họrọ ihe ị na-etinye maka ubochi 7",up:"ELU - Ọnụ ahịa ga-arịgo",drop:"DADA - Ọnụ ahịa ga-agbada",steady:"KWỤ OTU EBƏ - Ọnụ ahịa ga-adịgide",withdrawTitle:"WEPỤ - Min 50k + kpọọ 5",withdrawDesc:"Ị chọrọ 50k USDT + ndị enyi 5 akpọrọ ka ị wepụ",inviteTitle:"KPỌỌ 10 USDT",placeBtn:"TINYE BET UBỌCHI 7",verifyBtn:"NYOCHAỊ ỊKWỤ ỤGWỌ",submitBtn:"NYE ARỊRỊỌ MWEPU",copy:"DETUO ADREESỊ",addrBox:"Ziga na adreesị a:"}
};

LANGS.forEach(l=>{
  if(!T[l.c]){
    let base = JSON.parse(JSON.stringify(T['en']));
    if(l.c==='ar') base={...base,bets:"رهانات هذا الأسبوع - 7 أيام",placeBtn:"ضع رهان 7 أيام",copy:"نسخ العنوان",addrBox:"أرسل إلى هذا العنوان:"};
    if(l.c==='hi') base={...base,bets:"इस सप्ताह के दांव - 7 दिन",placeBtn:"7 दिनों के लिए दांव लगाएं",copy:"पता कॉपी करें",addrBox:"इस पते पर भेजें:"};
    if(l.c==='zh') base={...base,bets:"本周投注 - 7天",placeBtn:"投注7天",copy:"复制地址",addrBox:"发送到此地址:"};
    if(l.c==='pt') base={...base,bets:"APOSTAS ESTA SEMANA - 7 dias",placeBtn:"APOSTAR 7 DIAS"};
    if(l.c==='de') base={...base,bets:"WETTEN DIESE WOCHE - 7 Tage",placeBtn:"WETTE FÜR 7 TAGE PLATZIEREN"};
    if(l.c==='tr') base={...base,bets:"BU HAFTA BAHİSLER - 7 gün",placeBtn:"7 GÜN BAHİS YAP"};
    T[l.c]=base;
  }
});

function getText(k,code){
  let lang = code || localStorage.getItem('lang') || 'en';
  let d = T[lang] || T['en'];
  return d[k] || T['en'][k] || k;
}
function applyLang(code){
  let lang = code || localStorage.getItem('lang') || 'en';
  localStorage.setItem('lang',lang);
  document.querySelectorAll('[data-i18n]').forEach(el=>{
    let k = el.getAttribute('data-i18n');
    let txt = getText(k,lang);
    if(txt) el.innerText = txt;
  });
  let curEl = document.getElementById('curLangTop');
  if(curEl) curEl.innerText = lang.toUpperCase();
}
// init on load
document.addEventListener('DOMContentLoaded',()=>{ applyLang(localStorage.getItem('lang')||'en'); });
